[package]
name = "shunyata"
version = "0.1.0"
authors = ["Erick Daniel Corona"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
