version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Build for testing
          command: cargo build

  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Test code
          command: cargo test

  build-release:
    requires:
      - test
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build --release
