version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Build for testing
          command: cargo build

  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Test code
          command: cargo test
      - store_test_results:
          path: test-results

  release:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo build --release

workflows:
  build-test-release:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test